### ISSUE TITLE
How to access header values with the Push api ?

### ISSUE THREAD

**Issue by fenix01** [thmeitz/ksqldb-go#28]
Hi,

I am very new with go and I don't know how to access the values of the headerChannel from the push api example.

```
go func() {
		for row := range rowChannel {
			if row != nil {
				for row_col := range row {
					fieldn := row[row_col].(string)
					//var header ksqldb.Header
					header := <- headerChannel
					fmt.Printf("%+v\n",header)
					fmt.Printf("%d : %s\n", row_col, fieldn)
				}
				
				
			}
		}
		cancelFunction()
	}()
```
I did something like this in the go routine. The header values are displayed in the console :
{queryId:transient_USER_BEHAVIOR_4058313251310728391 columns:[{Name:EXE Type:STRING}]}

But I cannot access any field of the Header type. I have the following error `header.queryId undefined (type ksqldb.Header has no field or method` if I call this instruction :
`fmt.Printf("%s\n",header.queryId)`

Do you know what is the problem ?

I use go 1.18 with ksqldb-go v0.0.4

**Comment by thmeitz** [comment]
Hi @fenix01,

forget my previous answer, I was wrong.

https://github.com/thmeitz/ksqldb-go/blob/895ad659e4025274b4d4ddbaae941903525f078a/types.go#L90-L93

The Header contains Colum Data

https://github.com/thmeitz/ksqldb-go/blob/895ad659e4025274b4d4ddbaae941903525f078a/types.go#L96-L99

```go
fmt.Printf("%s\n",header.QueryId)
```
Here is the code how the header processing is working:

https://github.com/thmeitz/ksqldb-go/blob/895ad659e4025274b4d4ddbaae941903525f078a/pull.go#L115-L132

**Comment by fenix01** [comment]
Hi @thmeitz !
Thank you for your response. I tried to understand your current message and the first one. But I don't understand how I can access the column name with the headerChannel variable.
If I understand correctly you say that I should not be able to read from the header channel while processing the row channel. But my printf function is able to display the header from the row channel. But I cannot access the Columns field, neither its QueryId field.
I would like to parse a row and know what is the corresponding column name. But it doesn't work.

**Comment by fenix01** [comment]
Finally I found the problem @thmeitz !
I was using ksqldb-go in version v0.0.4 because it is the latest version in the release page. But in this version the Header struct is written like this.

https://github.com/thmeitz/ksqldb-go/blob/7babf9f0e1cdb9826cba4ff45844d9f1b82fb9a0/types.go#L113-L116

As you can see, all fields are in lowercase and are not exposed to the outside. So I cannot access columns field from my code.
It has been changed in the master branch :
https://github.com/thmeitz/ksqldb-go/blob/895ad659e4025274b4d4ddbaae941903525f078a/types.go#L90-L93

I added the library by pointing to the latest commit and now it works correctly.

`go get github.com/thmeitz/ksqldb-go@895ad659e4025274b4d4ddbaae941903525f078a`
