### ISSUE TITLE
Possible SQL Injection on ksqldb

### ISSUE THREAD

**Issue by gyosh** [thmeitz/ksqldb-go#29]
Hello,

It looks like SQL injection is still possible on ksqldb package if the parameter has single quotes in it.
```go
k := `SELECT TIMESTAMPTOSTRING(WINDOWSTART,'yyyy-MM-dd HH:mm:ss','Europe/London') AS WINDOW_START,
TIMESTAMPTOSTRING(WINDOWEND,'HH:mm:ss','Europe/London') AS WINDOW_END,
DOG_SIZE, DOGS_CT FROM DOGS_BY_SIZE
WHERE DOG_SIZE=?;`

stmnt, err := ksqldb.QueryBuilder(k, "middle' OR 'a'='a")
if err != nil {
	log.Fatal(err)
}
fmt.Println(*stmnt)
```
See: https://go.dev/play/p/4KoWROjK903

**Comment by thmeitz** [comment]
Hi @gyosh, could you please describe your use case?

I'll test your suggestion on line 114 in playground and check how that was solved in the database/sql package.

**Comment by thmeitz** [comment]
@gyosh: your use case is covered by a test now, please pull the latest master
