### ISSUE TITLE
[utils] SanitizeQuery only works when there is a space after \n

### ISSUE THREAD

**Issue by tothandras** [thmeitz/ksqldb-go#36]
We ran into SQL syntax problems with executing queries when the raw string literal doesn't contain spaces after `\n`.

eg.:

```go
q := `CREATE STREAM IF NOT EXISTS DOGS (ID STRING KEY,
	NAME STRING,
	DOGSIZE STRING,
	AGE STRING)
WITH (KAFKA_TOPIC='dogs',
VALUE_FORMAT='JSON', PARTITIONS=1);
`
```

instead of:
```go
q := `CREATE STREAM IF NOT EXISTS DOGS (ID STRING KEY, 
	NAME STRING, 
	DOGSIZE STRING, 
	AGE STRING) 
WITH (KAFKA_TOPIC='dogs', 
VALUE_FORMAT='JSON', PARTITIONS=1);
`
```

I think it's very error-prone, and the [`SanitizeQuery`](https://github.com/thmeitz/ksqldb-go/blob/11ab9aebb96af69a624de44704940a890a47edbc/internal/utils.go#L44) function should replace `\t` and `\n` with ` `.

**Comment by thmeitz** [comment]
Thanks for your bug report. Ill write a test and fix it...

**Comment by thmeitz** [comment]
@tothandras could you please test it? If everything works as expected Ill release it...

**Comment by tothandras** [comment]
@thmeitz Thank you for the quick response, I'll try it! Wouldn't it be better to do something like this instead?
```go
r := regexp.MustCompile(`\s+`)
s := r.ReplaceAllString(query, " ")
```

**Comment by thmeitz** [comment]
Hello @tothandras, I followed your suggestion.

**Comment by tothandras** [comment]
Thank you, @thmeitz!

**Comment by tothandras** [comment]
Now that I think about it, it'll also replace whitespace characters in `"  some  string "` on insert queries, for example. Do we even need SanitizeQuery?

**Comment by thmeitz** [comment]
SanitizeQuery was originally intended to do much more than just replace newlines and tabs. In the current use case it will remove the spaces and replace them with a single space. This will also process the string correctly, giving it its smallest possible length. For this reason I had written a test that exactly maps the use case. (see here: https://github.com/thmeitz/ksqldb-go/blob/main/internal/utils_test.go#L54-L61)
