### ISSUE TITLE
Add support for context

### ISSUE THREAD

**Issue by sagikazarmark** [thmeitz/ksqldb-go#38]
Currently, there is no way to propagate a context to HTTP requests which means that the client does not respect cancellations and timeouts and tracing is also not possible.

Generally, context support can be added in a backwards compatible way by creating new functions for each request, attaching `Context` or `Ctx` as a suffix.

Would you be open to accepting a contribution with this change?

**Comment by thmeitz** [comment]
Of course I am open to your PR!

**Comment by sagikazarmark** [comment]
@thmeitz do you prefer to keep backwards compatibility or should I just add context parameters to existing functions. Asking because of the notice in the readme saying the API is not stable.

**Comment by sagikazarmark** [comment]
Also, some of the existing methods already have a context parameter.

**Comment by thmeitz** [comment]
I will release a new v0.0.7 with the latest changes (today or tomorrow). We will then put your changes into the release v0.1.0.  
Important for me is that the tests run correctly. If you need help with the test, drop me a line.

So you can change the existing functions.

**Comment by thmeitz** [comment]
released v0.0.7, please update your fork

**Comment by sagikazarmark** [comment]
Thanks!
